# UNIT TESTING PLANNING


# TEST FUNCTION TO PULL ALL AVAILIBLE STARSHIPS FROM API

# TEST FUNCTION TO CHECK INTO THE URL AND EXTRACT ALL STARSHIPS TO EXTRACT ALL AVAILIBLE DATA

# TEST FUNCTION TO REPLACE THE PILOT KEY WITH OBJJECT ID

# TEST FUNCTION TO INSERT STARSHIPS INTO THEIR OWN COLLECTION IN MONGODB